# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Rahmane Ousmane
tagline:          'Personal blog'
description:      'On web development and software engineering'
url:              https://ousmane.dev/
baseurl:          /

author:
  name:           'Rahmane Ousmane'
  url:            https://github.com/ousmanedev

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ousmanedev

plugins:
  - jekyll-gist
  - jekyll-paginate